apiVersion: v1
kind: ConfigMap
metadata:
  name: start-runner
  namespace: github-runner-qrc-gen-email
data:
  start.sh: |-
    #!/bin/bash
    
    # Install HELM
    echo " - 🛳️ Installing HELM..."
    sudo apt-get install curl gpg apt-transport-https --yes
    curl -fsSL https://packages.buildkite.com/helm-linux/helm-debian/gpgkey | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    echo "deb [signed-by=/usr/share/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    sudo apt-get update
    sudo apt-get install helm --yes
    echo " - 🛳️ HELM installed successfully."
    
    # Install kubectl
    echo " - 🛳️ Installing kubectl..."
    sudo apt-get update
    # apt-transport-https may be a dummy package; if so, you can skip that package
    sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.35/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    sudo chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg # allow unprivileged APT programs to read this keyring
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.35/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
    sudo chmod 644 /etc/apt/sources.list.d/kubernetes.list   # helps tools such as command-not-found to work correctly
    sudo apt-get update
    sudo apt-get install -y kubectl
    echo " - 🛳️ kubectl installed successfully."
    
    REPOSITORY=$REPO
    ACCESS_TOKEN=$TOKEN
    echo "REPO ${REPOSITORY}"
    echo "ACCESS_TOKEN ${ACCESS_TOKEN}"
    REG_TOKEN=$(curl -X POST -H "Authorization: token ${ACCESS_TOKEN}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${REPOSITORY}/actions/runners/registration-token | jq .token --raw-output)
    echo "REG_TOKEN ${REG_TOKEN}"
    cd /home/runner
    ./config.sh --url https://github.com/${REPOSITORY} --token ${REG_TOKEN} --label ash
    cleanup() {
        echo "Removing runner..."
        ./config.sh remove --unattended --token ${REG_TOKEN}
    }
    trap 'cleanup; exit 130' INT
    trap 'cleanup; exit 143' TERM
    ./run.sh & wait $!
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: github-runner-qrc-gen-email
  name: runner
  labels:
    app: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runner
  template:
    metadata:
      name: runner
      labels:
        app: runner
    spec:
      containers:
        # - name: dind-service
        #   image: docker:dind
        #   securityContext:
        #     privileged: true
        #   env:
        #   - name: DOCKER_HOST
        #     value: tcp://localhost:2376 # Expose Docker daemon via TCP
        #   - name: DOCKER_TLS_CERTDIR
        #     value: ""
        #   volumeMounts:
        #   - name: docker-graph-storage
        #     mountPath: /var/lib/docker
        - name: dind-service
          image: docker:dind
          # Run the Docker daemon with TLS disabled for local communication within the pod
          command: ["dockerd-entrypoint.sh"] 
          args: ["--tls=false"] 
          securityContext:
            privileged: true # Required for DinD to work correctly
          env:
          # - name: DOCKER_HOST
          #   value: tcp://localhost:2376 # Expose Docker daemon via TCP
          - name: DOCKER_TLS_CERTDIR
            value: ""
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
        - name: actions-runner
          image: ghcr.io/actions/actions-runner:latest
          # image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner-dind:latest
          command: ["/home/runner/start.sh"]
          securityContext:
            privileged: true
          envFrom:
            - secretRef:
                name: github-runner-secret
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2375 # Client connects to the DinD service on localhost
          volumeMounts:
            - name: config
              mountPath: /home/runner/start.sh
              subPath: start.sh
              readOnly: true
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      volumes:
        - name: config
          configMap:
            name: start-runner
            defaultMode: 0744
        - name: docker-graph-storage
          emptyDir: {}